# action.yml
name: 'Push to Artifactory'
description: 'Leverages Github Secrets and Twine to push to private Artifactory server.'
inputs:
  artifactory-user:
    description: 'Artifactory username. Get one here: <link to where to get one>'
    required: true
  artifactory-token:
    description: 'Artifactory Acccess Token'
    required: true
  artifactory-url:
    description: 'Base URL for artifactory instance. Do NOT include repository in path'
    required: true
    default: ''
  artifactory-repo:
    description: 'Artifactory Repo to upload package to'
    required: true
    default: "${{ env.GITHUB_REPOSITORY }}"
  package-path:
    description: 'Path to the package artifact we want to upload'
    required: true
    default: "dist/*"
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - {{ inputs.artifactory-user }}
    - {{ inputs.artifactory-token }}
    - {{ inputs.artifactory-url }}
    - {{ inputs.artifactory-repo }}
    - {{ inputs.package-path }}
